name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        shell: bash
        run: |
          flake8 .

      - name: Check formatting with black
        shell: bash
        run: |
          black --check .

      - name: Run tests with coverage
        shell: bash
        run: |
          coverage run -m pytest
          coverage report

      - name: Generate HTML coverage report
        shell: bash
        run: coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Run build script
        shell: bash
        run: bash build.sh

      - name: Run deploy script
        shell: bash
        run: bash deploy.sh
